version: '3'

services:
  service.browserless:
    image: chromedp/headless-shell
    restart: always
    ports:
      - "9222:9222"
  service.golang:
    image: jasongwq/headless
    restart: always
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    volumes:
      - $PWD/app/:/go/src/app
