version: '3'

services:
  service.browserless:
    image: chromedp/headless-shell
    restart: always
    command:
      - --no-first-run
      #- --proxy-server=111.75.223.9:30646 --allow-insecure-localhost --ignore-ssl-errors=true --ignore-certificate-errors --allow-running-insecure-content
    ports:
      - "9222:9222"
  service.golang:
    image: jasongwq/headless
    restart: always
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    #command: 
    #  - bash
    volumes:
      - $PWD/app/:/go/src/app_tmp
